name: atac_analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.12.1
  - trimmomatic=0.39
  - bowtie2=2.5.2
  - samtools=1.18
  - picard=3.1.1
  - bedtools=2.31.0
  - macs2=2.2.9.1
  - bioconductor-diffbind=3.10.0
  - r-base=4.3
  - python=3.11 